setup(
    name="py-financas",
    version="1.0.0",
    description="Controle de finanças em Python",
    long_description=README,
    long_description_content_type="text/markdown",
    url="https://github.com/jaymealonso/py-financas",
    author="Jayme",
    author_email="",
    license="MIT",
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
    ],
    packages=["py-financas"],
    include_package_data=True,
    install_requires=["feedparser", "html2text", "importlib_resources", "typing"],
    entry_points={"console_scripts": ["py-financas=main:main"]},
)
